name: 'Azure Cost Estimator'
description: 'Runs cost estimation of Azure resources using Azure Cost Estimator tool'
inputs:
  template-file:
    description: 'Path to a template file containing Azure resources to estimate'
    required: true
  subscription-id:
    description: 'Azure subscription ID'
    required: false
  resource-group-name:
    description: 'Azure resource group name'
    required: false
  management-group-id:
    description: 'Azure management group ID'
    required: false
  tenant-id:
    description: 'Azure tenant ID'
    required: false
  location:
    description: 'Deployment location'
    required: false
  deployment-mode:
    description: 'Deployment mode'
    required: false
  threshold:
    description: 'Cost threshold'
    required: false
  parameters-file:
    description: 'Path to a parameters file'
    required: false
  currency:
    description: 'Selected currency'
    required: false
  generate-json-output:
    description: 'Should generate JSON output'
    required: false
  silent:
    description: 'Should run in silent mode'
    required: false
  stdout:
    description: 'Should print output to stdout'
    required: false
  disable-detailed-metrics:
    description: 'Should disable detailed metrics'
    required: false
  json-output-filename:
    description: 'Name of the JSON output file'
    required: false
  generate-html-output:
    description: 'Should generate HTML output'
    required: false
  inline-parameters:
    description: 'List of inline parameters'
    required: false
  dry-run:
    description: 'Should run in dry run mode'
    required: false
  output-format:
    description: 'Which output format to use'
    required: false
  disable-cache:
    description: 'Should disable cache'
    required: false
  terraform-executable-path:
    description: 'Path to Terraform executable'
    required: false
  conversion-rate:
    description: 'Selected conversion rate'
    required: false
  cache-handler:
    description: 'Selected cache handler'
    required: false
  cache-storage-account-name:
    description: 'Selected cache storage account name'
    required: false
  webhook-url:
    description: 'URL of the webhook to call'
    required: false
  webhook-authorization:
    description: 'Value of the authorization header to use when calling the webhook'
    required: false
  configuration-file:
    description: 'Path to a configuration file'
    required: false
  disable-version-check:
    description: 'Should disable version check'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
